name: Build Debug APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Show wrapper file
        run: |
          echo "=== gradle-wrapper.properties ==="
          cat gradle/wrapper/gradle-wrapper.properties

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Set Gradle home (local cache inside workspace)
        run: echo "GRADLE_USER_HOME=${{ github.workspace }}/.gradle" >> $GITHUB_ENV

      - name: Build Debug APK
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/*.apk
