name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK
        run: |
          sudo mkdir -p /usr/lib/android-sdk/cmdline-tools
          cd /usr/lib/android-sdk/cmdline-tools
          sudo curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o cmdtools.zip
          sudo unzip -q cmdtools.zip -d latest
          sudo rm cmdtools.zip
          echo "ANDROID_SDK_ROOT=/usr/lib/android-sdk" >> $GITHUB_ENV
          echo "PATH=/usr/lib/android-sdk/cmdline-tools/latest/bin:/usr/lib/android-sdk/platform-tools:/usr/lib/android-sdk/emulator:\$PATH" >> $GITHUB_ENV
          yes | sudo /usr/lib/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null

      - name: Install platforms and build-tools
        run: |
          /usr/lib/android-sdk/cmdline-tools/latest/bin/sdkmanager \
            "platforms;android-34" "build-tools;34.0.0" > /dev/null

      - name: Build Release APK
        working-directory: android
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ggvibe-ai-apk
          path: android/app/build/outputs/apk/release/*.apk
          if-no-files-found: warn
