name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Install required SDK components
        run: |
          sdkmanager --install "platform-tools" \
                              "platforms;android-34" \
                              "build-tools;34.0.0"

      - name: Install Gradle 8.7
        run: |
          wget -q https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q gradle-8.7-bin.zip
          echo "$PWD/gradle-8.7/bin" >> $GITHUB_PATH

      - name: Build Release APK
        working-directory: android
        run: |
          gradle --version
          gradle assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ggvibe-ai-apk
          path: android/app/build/outputs/apk/release/*.apk
          if-no-files-found: warn
